---

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-gloo.yml'
  ansible.builtin.import_playbook: playbook-gloo.yml

- name: 'Run playbook-nginx.yml'
  ansible.builtin.import_playbook: playbook-nginx.yml
