---
- name: 'Install, configure and start k3s'
  hosts: 'k3s1'
  gather_facts: true
  become: true
  module_defaults:
    kubernetes.core.helm:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s_info:
      kubeconfig: './k3s-kubeconfig'

  roles:

    - role: 'johanneskastl.install_k3s'
      tls_san:
        - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        - "k3s.{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}.sslip.io"
      disable_something: 'traefik'

  post_tasks:

    - name: 'Wait until all pods are running'
      delegate_to: localhost
      become: false
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: kube-system
      register: pod_list
      until:
        '
        pod_list | json_query("resources[*].status.phase") | unique | sort == ["Running"]
        or
        pod_list | json_query("resources[*].status.phase") | unique | sort == ["Running", "Succeeded"]
        '
      retries: 12
      delay: 10

    - name: 'Wait until all pods are ready'
      delegate_to: localhost
      become: false
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: kube-system
      register: pod_list_ready
      until:
        '
        pod_list_ready | json_query("resources[*].status.containerStatuses[*].ready") | unique | sort == [[true]]
        '
      retries: 12
      delay: 10
